export {
 RiDiscordFill as IDiscordFill,
 RiGoogleFill as IGoogleFill,
 RiTwitterFill as ITwitterFill,
 RiSearchLine as ISearchLine,
 RiSearchFill as ISearchFill,
 RiDeleteBin7Fill as IDeleteFill,
 RiDeleteBin7Line as IDeleteLine,
 RiLoginCircleLine as ILoginLine,
 RiLogoutCircleLine as ILogoutLine,
 RiHomeLine as IHomeLine,
 RiHomeFill as IHomeFill,
 RiUser3Line as IUserLine,
 RiUser3Fill as IUserFill,
 RiMore2Line as IMoreLine,
 RiErrorWarningLine as IWarningLine,
 RiCheckFill as ICheckmarkFill,
 RiArrowDownSLine as IArrowDownLine,
 RiPencilFill as ICreateFill,
 RiPencilLine as ICreateLine,
 RiSettings3Line as ISettingsLine,
 RiSettings3Fill as ISettingsFill,
 RiArrowLeftSLine as IBackLine,
 RiArrowLeftSFill as IBackFill,
 RiFunctionLine as IGridLine,
 RiFunctionFill as IGridFill,
 RiThumbUpLine as IThumbUpLine,
 RiThumbUpFill as IThumbUpFill,
} from "react-icons/ri";

export { HiOutlineHeart as IHeartLine, HiHeart as IHeartFill } from "react-icons/hi2";
